export const EVENTS = {
  RESUME_ANALYZED: 'RESUME_ANALYZED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  INTERVIEW_COMPLETED: 'INTERVIEW_COMPLETED',
  ONBOARDING_COMPLETED: 'ONBOARDING_COMPLETED',
  JOB_SELECTED: 'JOB_SELECTED',
  SKILL_UPDATED: 'SKILL_UPDATED'
};
